-- ==============================================================================
-- XMFCLUB - Complete Supabase Database Schema & Storage Setup
-- ==============================================================================
-- This script contains all DDL, DML, Indexes, Row Level Security (RLS) policies,
-- and Storage Bucket definitions required to set up a brand new Supabase project.
-- 
-- How to apply:
-- 1. Open your Supabase project dashboard: https://supabase.com/dashboard
-- 2. Go to "SQL Editor" in the left sidebar.
-- 3. Click "New query", paste the entire contents of this file, and click "Run".
-- ==============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 1. TABLES (DDL)
-- ==============================================================================

-- 1.1. App Settings Table
CREATE TABLE IF NOT EXISTS public.app_settings (
    id TEXT PRIMARY KEY,
    branches JSONB DEFAULT '[]'::jsonb NOT NULL,
    belts JSONB DEFAULT '[]'::jsonb NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.2. Members Table
CREATE TABLE IF NOT EXISTS public.members (
    member_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    dob DATE,
    age INTEGER,
    phone TEXT,
    email TEXT,
    role TEXT DEFAULT 'student' NOT NULL, -- 'student', 'instructor', 'volunteer', 'admin'
    belt TEXT DEFAULT 'White' NOT NULL,
    member_status TEXT DEFAULT 'Active' NOT NULL, -- 'Active', 'Inactive', 'Discontinued'
    fee_status TEXT DEFAULT 'Paid' NOT NULL, -- 'Paid', 'Pending', 'Overdue'
    password TEXT NOT NULL DEFAULT '12345',
    address TEXT,
    pin_code TEXT, -- Residential address PIN / postal code
    branch TEXT DEFAULT 'XMF Main HQ',
    blood_group TEXT,
    date_of_joining DATE DEFAULT CURRENT_DATE,
    date_of_leaving DATE,
    achievements TEXT,
    instructor_remarks TEXT,
    instructor_remarks_color TEXT DEFAULT 'green',
    actual_fee NUMERIC(10, 2) DEFAULT 0,
    fee_detail TEXT,
    due_date DATE,
    pending_amount NUMERIC(10, 2) DEFAULT 0,
    photo_url TEXT,
    is_reviewed BOOLEAN DEFAULT false NOT NULL,
    is_deleted BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.3. Attendance Table
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id TEXT NOT NULL REFERENCES public.members(member_id) ON UPDATE CASCADE ON DELETE CASCADE,
    belt TEXT,
    timestamp TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.4. Events Table
CREATE TABLE IF NOT EXISTS public.events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    target_belt TEXT DEFAULT 'All',
    date TIMESTAMPTZ NOT NULL,
    time TEXT DEFAULT '10:00',
    fee NUMERIC(10, 2) DEFAULT 0,
    fee_breakup JSONB DEFAULT '{"total": 0}'::jsonb,
    venue_name TEXT DEFAULT 'XMF Main HQ',
    venue_map_url TEXT,
    banner_url TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.5. Event Registrations Table
CREATE TABLE IF NOT EXISTS public.event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    member_id TEXT NOT NULL REFERENCES public.members(member_id) ON UPDATE CASCADE ON DELETE CASCADE,
    status TEXT DEFAULT 'Registered' NOT NULL,
    registered_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_event_member UNIQUE (event_id, member_id)
);

-- 1.6. Sequences for Crockford Base32 Batch Indices (starts at 0)
CREATE SEQUENCE IF NOT EXISTS public.qrc_batch_seq START 0 MINVALUE 0;
CREATE SEQUENCE IF NOT EXISTS public.tag_batch_seq START 0 MINVALUE 0;

-- 1.7. Batches Table (Fixed 32 items per batch)
CREATE TABLE IF NOT EXISTS public.credential_batches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    batch_number INTEGER NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('qrc', 'tag')),
    quantity INTEGER NOT NULL DEFAULT 32 CHECK (quantity = 32),
    start_token TEXT NOT NULL,
    end_token TEXT NOT NULL,
    configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by TEXT REFERENCES public.members(member_id),
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_batch_per_type UNIQUE (type, batch_number)
);

-- 1.8. Reusable Physical Credentials Table
CREATE TABLE IF NOT EXISTS public.credentials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT NOT NULL CHECK (type IN ('qrc', 'tag')),
    token TEXT NOT NULL, -- 6-digit Crockford Base32 (e.g. 000000, 000010)
    status TEXT NOT NULL DEFAULT 'free' CHECK (status IN ('free', 'assigned', 'deleted')),
    batch_id UUID REFERENCES public.credential_batches(id),
    physical_uid TEXT, -- Manufacturer chip UID (e.g. 04:A3:91:72:8C:11)
    rejection_reason TEXT, -- 'printing_error', 'damaged', 'misaligned', 'chip_failure', 'other'
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_token_per_type UNIQUE (type, token)
);

-- 1.9. Credential Assignments Table (Audit & Active Linkage)
CREATE TABLE IF NOT EXISTS public.credential_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    credential_id UUID NOT NULL REFERENCES public.credentials(id) ON DELETE CASCADE,
    member_id TEXT NOT NULL REFERENCES public.members(member_id) ON UPDATE CASCADE ON DELETE CASCADE,
    assigned_by TEXT REFERENCES public.members(member_id),
    assigned_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    unassigned_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- 2. INDEXES
-- ==============================================================================
CREATE UNIQUE INDEX IF NOT EXISTS one_active_assignment_per_credential ON public.credential_assignments(credential_id) WHERE unassigned_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_credential_assignments_member_id ON public.credential_assignments(member_id);
CREATE INDEX IF NOT EXISTS idx_credentials_status ON public.credentials(status);
CREATE INDEX IF NOT EXISTS idx_credentials_token ON public.credentials(token);

CREATE INDEX IF NOT EXISTS idx_members_member_id ON public.members(member_id);
CREATE INDEX IF NOT EXISTS idx_members_phone ON public.members(phone);
CREATE INDEX IF NOT EXISTS idx_members_is_deleted ON public.members(is_deleted);
CREATE INDEX IF NOT EXISTS idx_members_is_reviewed ON public.members(is_reviewed);
CREATE INDEX IF NOT EXISTS idx_members_belt ON public.members(belt);
CREATE INDEX IF NOT EXISTS idx_members_branch ON public.members(branch);
CREATE INDEX IF NOT EXISTS idx_members_pin_code ON public.members(pin_code);
CREATE INDEX IF NOT EXISTS idx_members_created_at ON public.members(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_attendance_member_id ON public.attendance(member_id);
CREATE INDEX IF NOT EXISTS idx_attendance_timestamp ON public.attendance(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_events_date ON public.events(date ASC);
CREATE INDEX IF NOT EXISTS idx_event_registrations_event_id ON public.event_registrations(event_id);
CREATE INDEX IF NOT EXISTS idx_event_registrations_member_id ON public.event_registrations(member_id);

-- ==============================================================================
-- 3. STORAGE BUCKET & STORAGE POLICIES
-- ==============================================================================
-- Create the public storage bucket for student & member photos
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'member-photos',
    'member-photos',
    true,
    10485760, -- 10MB limit per image
    ARRAY['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
    public = true,
    file_size_limit = 10485760,
    allowed_mime_types = ARRAY['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif'];

-- Drop existing storage policies if re-running
DROP POLICY IF EXISTS "Public Access Member Photos" ON storage.objects;
DROP POLICY IF EXISTS "Allow Uploads Member Photos" ON storage.objects;
DROP POLICY IF EXISTS "Allow Updates Member Photos" ON storage.objects;
DROP POLICY IF EXISTS "Allow Deletes Member Photos" ON storage.objects;

-- 3.1. Public Read Policy on member-photos
CREATE POLICY "Public Access Member Photos"
ON storage.objects FOR SELECT
USING (bucket_id = 'member-photos');

-- 3.2. Public/Anon Insert Policy on member-photos
CREATE POLICY "Allow Uploads Member Photos"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'member-photos');

-- 3.3. Public/Anon Update Policy on member-photos
CREATE POLICY "Allow Updates Member Photos"
ON storage.objects FOR UPDATE
USING (bucket_id = 'member-photos');

-- 3.4. Public/Anon Delete Policy on member-photos
CREATE POLICY "Allow Deletes Member Photos"
ON storage.objects FOR DELETE
USING (bucket_id = 'member-photos');

-- ==============================================================================
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
-- Enable RLS on all application tables
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registrations ENABLE ROW LEVEL SECURITY;

-- 4.1. app_settings policies (read/write for all client sessions)
DROP POLICY IF EXISTS "Public read app_settings" ON public.app_settings;
DROP POLICY IF EXISTS "Public write app_settings" ON public.app_settings;
CREATE POLICY "Public read app_settings" ON public.app_settings FOR SELECT USING (true);
CREATE POLICY "Public write app_settings" ON public.app_settings FOR ALL USING (true) WITH CHECK (true);

-- 4.2. members policies
DROP POLICY IF EXISTS "Public read members" ON public.members;
DROP POLICY IF EXISTS "Public insert members" ON public.members;
DROP POLICY IF EXISTS "Public update members" ON public.members;
DROP POLICY IF EXISTS "Public delete members" ON public.members;
CREATE POLICY "Public read members" ON public.members FOR SELECT USING (true);
CREATE POLICY "Public insert members" ON public.members FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update members" ON public.members FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete members" ON public.members FOR DELETE USING (true);

-- 4.3. attendance policies
DROP POLICY IF EXISTS "Public read attendance" ON public.attendance;
DROP POLICY IF EXISTS "Public insert attendance" ON public.attendance;
DROP POLICY IF EXISTS "Public update attendance" ON public.attendance;
DROP POLICY IF EXISTS "Public delete attendance" ON public.attendance;
CREATE POLICY "Public read attendance" ON public.attendance FOR SELECT USING (true);
CREATE POLICY "Public insert attendance" ON public.attendance FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update attendance" ON public.attendance FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Public delete attendance" ON public.attendance FOR DELETE USING (true);

-- 4.4. events policies
DROP POLICY IF EXISTS "Public read events" ON public.events;
DROP POLICY IF EXISTS "Public write events" ON public.events;
CREATE POLICY "Public read events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Public write events" ON public.events FOR ALL USING (true) WITH CHECK (true);

-- 4.5. event_registrations policies
DROP POLICY IF EXISTS "Public read event_registrations" ON public.event_registrations;
DROP POLICY IF EXISTS "Public write event_registrations" ON public.event_registrations;
CREATE POLICY "Public read event_registrations" ON public.event_registrations FOR SELECT USING (true);
CREATE POLICY "Public write event_registrations" ON public.event_registrations FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- 4.6. credential_batches policies
ALTER TABLE public.credential_batches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read credential_batches" ON public.credential_batches;
DROP POLICY IF EXISTS "Staff insert batches" ON public.credential_batches;
CREATE POLICY "Public read credential_batches" ON public.credential_batches FOR SELECT USING (true);
CREATE POLICY "Staff insert batches" ON public.credential_batches FOR INSERT WITH CHECK (true);

-- 4.7. credentials policies
ALTER TABLE public.credentials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read credentials" ON public.credentials;
DROP POLICY IF EXISTS "Staff insert credentials" ON public.credentials;
DROP POLICY IF EXISTS "Staff update credentials" ON public.credentials;
CREATE POLICY "Public read credentials" ON public.credentials FOR SELECT USING (true);
CREATE POLICY "Staff insert credentials" ON public.credentials FOR INSERT WITH CHECK (true);
CREATE POLICY "Staff update credentials" ON public.credentials FOR UPDATE USING (true) WITH CHECK (true);

-- 4.8. credential_assignments policies
ALTER TABLE public.credential_assignments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read credential_assignments" ON public.credential_assignments;
DROP POLICY IF EXISTS "Staff insert assignments" ON public.credential_assignments;
DROP POLICY IF EXISTS "Staff update assignments" ON public.credential_assignments;
CREATE POLICY "Public read credential_assignments" ON public.credential_assignments FOR SELECT USING (true);
CREATE POLICY "Staff insert assignments" ON public.credential_assignments FOR INSERT WITH CHECK (true);
CREATE POLICY "Staff update assignments" ON public.credential_assignments FOR UPDATE USING (true) WITH CHECK (true);

