/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SocialRouteImport } from './routes/social'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingCurriculumRouteImport } from './routes/training/curriculum'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingCurriculumRoute = TrainingCurriculumRouteImport.update({
  id: '/training/curriculum',
  path: '/training/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/mcp': typeof McpRoute
  '/resources': typeof ResourcesRoute
  '/social': typeof SocialRoute
  '/store': typeof StoreRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/training/curriculum': typeof TrainingCurriculumRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/mcp': typeof McpRoute
  '/resources': typeof ResourcesRoute
  '/social': typeof SocialRoute
  '/store': typeof StoreRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/training/curriculum': typeof TrainingCurriculumRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/mcp': typeof McpRoute
  '/resources': typeof ResourcesRoute
  '/social': typeof SocialRoute
  '/store': typeof StoreRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/training/curriculum': typeof TrainingCurriculumRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/events'
    | '/mcp'
    | '/resources'
    | '/social'
    | '/store'
    | '/demo/better-auth'
    | '/demo/mcp-todos'
    | '/training/curriculum'
    | '/api/auth/$'
    | '/demo/api/mcp-todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/events'
    | '/mcp'
    | '/resources'
    | '/social'
    | '/store'
    | '/demo/better-auth'
    | '/demo/mcp-todos'
    | '/training/curriculum'
    | '/api/auth/$'
    | '/demo/api/mcp-todos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/events'
    | '/mcp'
    | '/resources'
    | '/social'
    | '/store'
    | '/demo/better-auth'
    | '/demo/mcp-todos'
    | '/training/curriculum'
    | '/api/auth/$'
    | '/demo/api/mcp-todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  McpRoute: typeof McpRoute
  ResourcesRoute: typeof ResourcesRoute
  SocialRoute: typeof SocialRoute
  StoreRoute: typeof StoreRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  TrainingCurriculumRoute: typeof TrainingCurriculumRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/curriculum': {
      id: '/training/curriculum'
      path: '/training/curriculum'
      fullPath: '/training/curriculum'
      preLoaderRoute: typeof TrainingCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  McpRoute: McpRoute,
  ResourcesRoute: ResourcesRoute,
  SocialRoute: SocialRoute,
  StoreRoute: StoreRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  TrainingCurriculumRoute: TrainingCurriculumRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
