/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SocialRouteImport } from './routes/social'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as JoinRouteImport } from './routes/join'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TrainingCurriculumRouteImport } from './routes/training/curriculum'
import { Route as SUuidRouteImport } from './routes/s/$uuid'
import { Route as DemoBookingRouteImport } from './routes/demo/booking'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingCurriculumRoute = TrainingCurriculumRouteImport.update({
  id: '/training/curriculum',
  path: '/training/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const SUuidRoute = SUuidRouteImport.update({
  id: '/s/$uuid',
  path: '/s/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBookingRoute = DemoBookingRouteImport.update({
  id: '/demo/booking',
  path: '/demo/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/resources': typeof ResourcesRoute
  '/social': typeof SocialRoute
  '/store': typeof StoreRoute
  '/admin/setup': typeof AdminSetupRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/booking': typeof DemoBookingRoute
  '/s/$uuid': typeof SUuidRoute
  '/training/curriculum': typeof TrainingCurriculumRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/resources': typeof ResourcesRoute
  '/social': typeof SocialRoute
  '/store': typeof StoreRoute
  '/admin/setup': typeof AdminSetupRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/booking': typeof DemoBookingRoute
  '/s/$uuid': typeof SUuidRoute
  '/training/curriculum': typeof TrainingCurriculumRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/resources': typeof ResourcesRoute
  '/social': typeof SocialRoute
  '/store': typeof StoreRoute
  '/admin/setup': typeof AdminSetupRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/booking': typeof DemoBookingRoute
  '/s/$uuid': typeof SUuidRoute
  '/training/curriculum': typeof TrainingCurriculumRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/contact'
    | '/events'
    | '/join'
    | '/resources'
    | '/social'
    | '/store'
    | '/admin/setup'
    | '/demo/better-auth'
    | '/demo/booking'
    | '/s/$uuid'
    | '/training/curriculum'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/contact'
    | '/events'
    | '/join'
    | '/resources'
    | '/social'
    | '/store'
    | '/admin/setup'
    | '/demo/better-auth'
    | '/demo/booking'
    | '/s/$uuid'
    | '/training/curriculum'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/auth'
    | '/contact'
    | '/events'
    | '/join'
    | '/resources'
    | '/social'
    | '/store'
    | '/admin/setup'
    | '/demo/better-auth'
    | '/demo/booking'
    | '/s/$uuid'
    | '/training/curriculum'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  JoinRoute: typeof JoinRoute
  ResourcesRoute: typeof ResourcesRoute
  SocialRoute: typeof SocialRoute
  StoreRoute: typeof StoreRoute
  AdminSetupRoute: typeof AdminSetupRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoBookingRoute: typeof DemoBookingRoute
  SUuidRoute: typeof SUuidRoute
  TrainingCurriculumRoute: typeof TrainingCurriculumRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/curriculum': {
      id: '/training/curriculum'
      path: '/training/curriculum'
      fullPath: '/training/curriculum'
      preLoaderRoute: typeof TrainingCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$uuid': {
      id: '/s/$uuid'
      path: '/s/$uuid'
      fullPath: '/s/$uuid'
      preLoaderRoute: typeof SUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/booking': {
      id: '/demo/booking'
      path: '/demo/booking'
      fullPath: '/demo/booking'
      preLoaderRoute: typeof DemoBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  JoinRoute: JoinRoute,
  ResourcesRoute: ResourcesRoute,
  SocialRoute: SocialRoute,
  StoreRoute: StoreRoute,
  AdminSetupRoute: AdminSetupRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoBookingRoute: DemoBookingRoute,
  SUuidRoute: SUuidRoute,
  TrainingCurriculumRoute: TrainingCurriculumRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
