/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SUuidRouteImport } from './routes/s/$uuid'
import { Route as DemoBookingRouteImport } from './routes/demo/booking'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SUuidRoute = SUuidRouteImport.update({
  id: '/s/$uuid',
  path: '/s/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBookingRoute = DemoBookingRouteImport.update({
  id: '/demo/booking',
  path: '/demo/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/events': typeof EventsRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/store': typeof StoreRoute
  '/admin/setup': typeof AdminSetupRoute
  '/demo/booking': typeof DemoBookingRoute
  '/s/$uuid': typeof SUuidRoute
  '/admin/': typeof AdminIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/events': typeof EventsRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/store': typeof StoreRoute
  '/admin/setup': typeof AdminSetupRoute
  '/demo/booking': typeof DemoBookingRoute
  '/s/$uuid': typeof SUuidRoute
  '/admin': typeof AdminIndexRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/events': typeof EventsRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/store': typeof StoreRoute
  '/admin/setup': typeof AdminSetupRoute
  '/demo/booking': typeof DemoBookingRoute
  '/s/$uuid': typeof SUuidRoute
  '/admin/': typeof AdminIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/events'
    | '/hall-of-fame'
    | '/login'
    | '/resources'
    | '/store'
    | '/admin/setup'
    | '/demo/booking'
    | '/s/$uuid'
    | '/admin/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/events'
    | '/hall-of-fame'
    | '/login'
    | '/resources'
    | '/store'
    | '/admin/setup'
    | '/demo/booking'
    | '/s/$uuid'
    | '/admin'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/events'
    | '/hall-of-fame'
    | '/login'
    | '/resources'
    | '/store'
    | '/admin/setup'
    | '/demo/booking'
    | '/s/$uuid'
    | '/admin/'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  EventsRoute: typeof EventsRoute
  HallOfFameRoute: typeof HallOfFameRoute
  LoginRoute: typeof LoginRoute
  ResourcesRoute: typeof ResourcesRoute
  StoreRoute: typeof StoreRoute
  AdminSetupRoute: typeof AdminSetupRoute
  DemoBookingRoute: typeof DemoBookingRoute
  SUuidRoute: typeof SUuidRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$uuid': {
      id: '/s/$uuid'
      path: '/s/$uuid'
      fullPath: '/s/$uuid'
      preLoaderRoute: typeof SUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/booking': {
      id: '/demo/booking'
      path: '/demo/booking'
      fullPath: '/demo/booking'
      preLoaderRoute: typeof DemoBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  EventsRoute: EventsRoute,
  HallOfFameRoute: HallOfFameRoute,
  LoginRoute: LoginRoute,
  ResourcesRoute: ResourcesRoute,
  StoreRoute: StoreRoute,
  AdminSetupRoute: AdminSetupRoute,
  DemoBookingRoute: DemoBookingRoute,
  SUuidRoute: SUuidRoute,
  AdminIndexRoute: AdminIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
