/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as MemberIdRouteImport } from './routes/$memberId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIdRoute = MemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$memberId': typeof MemberIdRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/store': typeof StoreRoute
  '/admin/': typeof AdminIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$memberId': typeof MemberIdRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/store': typeof StoreRoute
  '/admin': typeof AdminIndexRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$memberId': typeof MemberIdRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/store': typeof StoreRoute
  '/admin/': typeof AdminIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$memberId'
    | '/connect'
    | '/dashboard'
    | '/events'
    | '/hall-of-fame'
    | '/login'
    | '/resources'
    | '/store'
    | '/admin/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$memberId'
    | '/connect'
    | '/dashboard'
    | '/events'
    | '/hall-of-fame'
    | '/login'
    | '/resources'
    | '/store'
    | '/admin'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/$memberId'
    | '/connect'
    | '/dashboard'
    | '/events'
    | '/hall-of-fame'
    | '/login'
    | '/resources'
    | '/store'
    | '/admin/'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemberIdRoute: typeof MemberIdRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  HallOfFameRoute: typeof HallOfFameRoute
  LoginRoute: typeof LoginRoute
  ResourcesRoute: typeof ResourcesRoute
  StoreRoute: typeof StoreRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$memberId': {
      id: '/$memberId'
      path: '/$memberId'
      fullPath: '/$memberId'
      preLoaderRoute: typeof MemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemberIdRoute: MemberIdRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  HallOfFameRoute: HallOfFameRoute,
  LoginRoute: LoginRoute,
  ResourcesRoute: ResourcesRoute,
  StoreRoute: StoreRoute,
  AdminIndexRoute: AdminIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
