import jwt
from typing import Any
from app.core.config import settings

def decode_jwt_token(token: str) -> dict[str, Any] | None:
    """
    Decodes a stateless JWT token. 
    In our decoupled architecture, this token is generated by Better Auth on the TanStack frontend.
    The FastAPI backend shares the same SECRET_KEY to cryptographically verify the signature.
    """
    try:
        # We assume Better Auth issues standard HS256 JWTs or similar.
        decoded_token = jwt.decode(
            token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM]
        )
        return decoded_token
    except jwt.InvalidTokenError:
        # Invalid signature, expired token, etc.
        return None